title: SAS Grid Documentation
author: John Mathieu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 This Site will contain all end user documentation.
 This documentation is for providing assistance on setting up and 
 managing SAS Grid access and providing best practices to properly 
 use the platform.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
